# Generated by Django 4.1 on 2023-03-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_match_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='board',
            field=models.CharField(default='RNBQKBNRPPPPPPPP                                pppppppprnbqkbnr', max_length=64),
        ),
    ]
