# Generated by Django 4.1 on 2023-04-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_match_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='bk_can_castle',
            new_name='b_castle',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='wk_can_castle',
            new_name='w_castle',
        ),
    ]
